### ISSUE TITLE
Undefined flag emoji

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/coronavirus-map-dashboard#1]
If it doesn't exist, should not try to include it

![image](https://user-images.githubusercontent.com/1045274/80107587-42520600-8549-11ea-84f4-080575385e46.png)

**Comment by crc8109** [comment]
Had the same issue after I built off your first tutorial. I [destructed the info from the AP](https://github.com/crc8109/COVID19-World-Tracker/blob/master/src/pages/index.js)I so I could pull the wiki link to the PNGs itself (lines 46, 49-50) and it pulls an enigma flag to show it doesn't have a flag attached to it:
 
![image](https://user-images.githubusercontent.com/56422761/80559591-089b5800-89ac-11ea-92eb-e8facac2800b.png)

I know you said you'd rather it blank if no flag, but I thought this flag it showed kept the formatting consistent.

If you think this isn't what you're going for aesthetically, then I can take a look and see what I can figure out

**Comment by colbyfayock** [comment]
@crc8109 im okay either way! mostly wanted to fix the undefined issue. was only thinking of not showing a flag at all since it doesn't really have the right one there, but that represents that. if you want to take a stab at it you can choose :)

**Comment by crc8109** [comment]
@colbyfayock I took a look and it seems the main issue is getEmojiFlag. The API has MS Zaandam's country code as null. So when the function reads the code, it returns an undefined.

I'm honestly very very new to web dev, so I can't exactly figure out how to fix it. But I think destructuring the info under 'country info' so that 'flag', not country code is pulled. And then making the container with the stats pull the url for the png and setting that as an img tag.

https://github.com/crc8109/COVID19-World-Tracker/blob/master/src/pages/index.js

I probably didn't explain this too well but lines 46, 49-50, & 102 are what I'm trying to say.

Sorry I wasn't much help. But hopefully you're able to figure out how to manipulate getEmojiFlag so it returns something other than undefined

**Comment by colbyfayock** [comment]
no problem at all! what if we did something like:
```
let header = country;

if ( flag ) {
  header = `<img src="${flag}"> ${header}`;
}
```
Then inside the `stats` HTML we could do:
```
const stats = `
        <span class="icon-marker-tooltip">
          <h2>${header}</h2>
```

If you'd rather me hop in and fix it I can do that too :) but in case you wanted to take a shot

**Comment by crc8109** [comment]
Interesting. If you don't mind waiting, I'll take a look tomorrow and tinker with a bit to see if I can get it to work. Thanks for the tip,I really appreciate the guidance

**Comment by colbyfayock** [comment]
looks like it now shows a ? emoji flag so it's fixed ✅
